#!/bin/sh

echo -n "Surpass build started..."

SCRIPT_DIR=`dirname $0`

. $SCRIPT_DIR/localenv

JAVAC=javac
JAVA=java
JAR=jar
JLINK=jlink

CLASSES=build-output/classes
DIST=build-output/dist
LOG=build-output/log.txt

MODS=mods

rm -rf $CLASSES $DIST
rm -f $LOG
mkdir -p $CLASSES $DIST

$JAVAC --module-path $THIRD_PARTY_DEPS --module-source-path $MODS -d $CLASSES `find $MODS -name "*.java"` >> $LOG 2>&1 || {
    echo "compilation failed"
    exit 1
}

$JLINK --module-path $CLASSES:$JAVA_HOME/jmods --add-modules surpass.api,surpass.core,surpass.persist,surpass.app,surpass.gui --output $DIST/surpass --launcher surpass=surpass.gui/org.esoul.surpass.gui.Main \
      --strip-debug --compress 2 --no-header-files --no-man-pages >> $LOG 2>&1 || {
    echo "jlink failed"
    exit 3
}

echo done
