#!/bin/sh

BUILD_LIB=$SCRIPT_DIR/build-lib
mkdir -p $BUILD_LIB

REPO_URL=https://repo1.maven.org/maven2

DEPS="junit/junit/4.12/junit-4.12.jar \
      org/junit/jupiter/junit-jupiter-api/5.6.2/junit-jupiter-api-5.6.2.jar \
      org/junit/platform/junit-platform-commons/1.6.2/junit-platform-commons-1.6.2.jar \
      org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar \
      org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar"

if [ `uname -s` = "FreeBSD" ]
then
    fetch="fetch -q -o"
else
    fetch="wget -q -O"
fi

for dep in $DEPS
do
    local_dep=$BUILD_LIB/`basename $dep`
    if [ ! -f $local_dep ]
    then
        $fetch $local_dep $REPO_URL/$dep
    fi
done

for dep in `ls $BUILD_LIB`
do
    THIRD_PARTY_DEPS=$THIRD_PARTY_DEPS:$BUILD_LIB/$dep
done
