plugins {
    id "java"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":surpass.api")
    implementation project(":surpass.core")
    implementation project(":surpass.app")
    implementation project(":surpass.hello")

    runtimeOnly project(":surpass.persist")
    runtimeOnly project(":surpass.google.drive")

    implementation "com.formdev:flatlaf:3.7.2"
}

build.doLast {
    copy {
        from configurations.runtimeClasspath
        into "$buildDir/libs"
    }
}
